### ISSUE TITLE
Probeer geen <br> te gebruiken om te stylen

### ISSUE THREAD

**Issue by CathelijneVisser** [Davidvboxt/the-startup-responsive-interactieve-website#3]
https://github.com/Davidvboxt/the-startup-responsive-interactieve-website/blob/6043d424abb40ccbe4ff21574fbb81ded120aeeb/index.html#L96

**Comment by Davidvboxt** [comment]
Deze structuur is overgenomen van de live voorbeeld website van de vacatuurpagina van Avocado Media.
