### ISSUE TITLE
Don’t use html element <br> for styling

### ISSUE THREAD

**Issue by maikangn** [Davidvboxt/the-startup-responsive-interactieve-website#6]
https://github.com/Davidvboxt/the-startup-responsive-interactieve-website/blob/6043d424abb40ccbe4ff21574fbb81ded120aeeb/index.html#L129

Solve breaking rules with CSS

**Comment by Davidvboxt** [comment]
Deze structuur is overgenomen van de live voorbeeld website van de vacatuurpagina van Avocado Media.
