### ISSUE TITLE
Animatie voor button

### ISSUE THREAD

**Issue by CelinexPutte** [Davidvboxt/the-startup-responsive-interactieve-website#7]
Misschien leuk om iets met de `:hover` state te doen. Denk aan een scale of een kleur die veranderd. Dan is het duidelijker dat het klikbaar is.

https://github.com/Davidvboxt/the-startup-responsive-interactieve-website/blob/6043d424abb40ccbe4ff21574fbb81ded120aeeb/index.html#L35

**Comment by Davidvboxt** [comment]
De cursor: pointer maakt het al duidelijk genoeg voor mij om te laten zien dat het klikbaar is, toch bedankt voor je feedback!
